name = "trusight"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = ".next/static"

[env.production]
name = "trusight"
route = "trusight.your-domain.com/*"
zone_id = "your-zone-id"

[env.staging]
name = "trusight-staging"
route = "staging.trusight.your-domain.com/*"
zone_id = "your-zone-id"

# Environment variables (add your actual values)
[vars]
NODE_ENV = "production"

# KV namespaces (uncomment and configure if needed)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects (uncomment and configure if needed)
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# R2 buckets (uncomment and configure if needed)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
# preview_bucket_name = "my-bucket-preview"

# D1 databases (uncomment and configure if needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id"
